- .github/workflows/CI_branch_tagging.yml
- .github/workflows/CI_create_release_branch.yml
- .github/workflows/CI_make_helm_chart.yaml
- .github/workflows/CI_master_push.yml
- .github/workflows/CI_reflect_branch_update_to_master.yml
> Add github Actions

- src/spaceone/notification/conf/global_conf.py
spaceone.core.cache.local_cache.LocalCache ttl
> Update TTL at spaceone.core.cache.local_cache.LocalCache

- src/spaceone/notification/conf/protocol_conf.py
- src/spaceone/notification/error/channel.py
- src/spaceone/notification/service/project_channel_service.py
- src/spaceone/notification/service/user_channel_service.py
-- Update for bug fix is_subscribe
> bug fix regarding is_subscribe

- src/spaceone/notification/conf/proto_conf.py
- src/spaceone/notification/info/__init__.py
- src/spaceone/notification/info/notification_info.py
- src/spaceone/notification/info/project_channel_info.py
- src/spaceone/notification/info/user_channel_info.py
- src/spaceone/notification/interface/grpc/v1/__init__.py
- src/spaceone/notification/interface/grpc/v1/notification.py
- src/spaceone/notification/manager/__init__.py
- src/spaceone/notification/manager/notification_manager.py
- src/spaceone/notification/model/__init__.py
- src/spaceone/notification/model/notification_model.py
- src/spaceone/notification/model/project_channel_model.py
- src/spaceone/notification/service/__init__.py
- src/spaceone/notification/service/notification_service.py
- src/spaceone/notification/service/project_channel_service.py
Add notification.Notification with proto
> Add notification.Notification

- src/spaceone/notification/service/project_channel_service.py
- src/spaceone/notification/service/user_channel_service.py
Notification 
- set_subscription
> --- Notification ---

- src/spaceone/notification/info/notification_info.py
- src/spaceone/notification/manager/notification_manager.py
- src/spaceone/notification/model/notification_model.py
- src/spaceone/notification/service/notification_service.py
> notification.Notification

- src/spaceone/notification/info/project_channel_info.py
- src/spaceone/notification/info/user_channel_info.py
> notification Schedule

- src/spaceone/notification/model/notification_model.py
- src/spaceone/notification/model/user_channel_model.py
- src/spaceone/notification/service/notification_service.py
- src/spaceone/notification/service/project_channel_service.py
- src/spaceone/notification/service/protocol_service.py
- src/spaceone/notification/service/user_channel_service.py
refactor: fix lint and change docs
> refactor: add USER scope for authorization

- src/spaceone/notification/service/notification_service.py
fix: update import core utils for overriding datetime module
#82
> fix: update import core utils for overriding datetime module

- src/spaceone/notification/service/__init__.py
feat: add notification quota / usage service
Add feature to metering and quota for sending notifications (#86)
> feat: add notification quota / usage service

- src/spaceone/notification/service/quota_service.py
fix: modify isinstance condition
Add feature to metering and quota for sending notifications(#86)
> fix: modify isinstance condition

- src/spaceone/notification/interface/grpc/v1/quota.py
> fix: modify create interface

- src/spaceone/notification/model/quota_model.py
- src/spaceone/notification/service/notification_service.py
fix: modify quota limit model
Add feature to metering and quota for sending notifications (#86)
> fix: modify quota limit model

- src/spaceone/notification/service/notification_service.py
> fix: modify error raise

- src/spaceone/notification/service/notification_service.py
> refactor: rename method

- src/spaceone/notification/service/notification_service.py
fix: modify dispatch noti
Add feature to metering and quota for sending notifications (#86)
> fix: modify dispatch noti

- src/spaceone/notification/service/notification_service.py
- src/spaceone/notification/service/quota_service.py
refactor: update valid check limit
Add feature to metering and quota for sending notifications (#86)
> refactor: update valid check limit

- src/spaceone/notification/error/quota.py
- src/spaceone/notification/service/notification_service.py
refactor: update Quota exceeded error message
> refactor: update Quota exceeded error message

- src/spaceone/notification/service/protocol_service.py
> fix: fix when pre-installing protocols

- deploy/helm/values.yaml
- src/spaceone/notification/interface/task/v1/delete_old_notification_scheduler.py
- src/spaceone/notification/service/notification_service.py
refactor: update old notification remove scheduler
> refactor: update old notification remove scheduler

- deploy/helm/Chart.yaml
- deploy/helm/config/config.yaml
> etc: update helm

- deploy/helm/config/config.yaml
- deploy/helm/values.yaml
etc: remove minute in scheduler conf
> etc: remove minute in scheduler conf

- deploy/helm/Chart.yaml
> etc: helm version up

- src/spaceone/notification/service/notification_service.py
> etc: add logger for debug

- src/spaceone/notification/service/notification_service.py
refactor: remove object parameter for worker
> refactor: remove object parameter for worker

- deploy/helm/values.yaml
etc: add QUEUE in application config
> etc: add QUEUE in application config

- deploy/helm/Chart.yaml
- deploy/helm/config/config.yaml
- deploy/helm/values.yaml
etc: arrange QUEUE in application config
> etc: arrange QUEUE in application config

- src/spaceone/notification/service/notification_service.py
> etc: refactor secret_data

- src/spaceone/notification/service/notification_service.py
fix:modify get_notification_usage method parameter
> fix:modify get_notification_usage method parameter

- src/spaceone/notification/service/notification_service.py
fix: modify check_quota method parameter
> fix: modify check_quota method parameter

- src/spaceone/notification/service/notification_service.py
refactor: move check_quota method in try block for fail_count
> refactor: move check_quota method in try block for fail_count

- deploy/helm/values.yaml
- src/spaceone/notification/service/notification_service.py
etc: update scheduler interval time to 60 (for test)
> etc: update scheduler interval time to 60 (for test)

- deploy/helm/Chart.yaml
> etc: version up

- deploy/helm/values.yaml
etc: update notification delete scheduler interval time (86400)
> etc: update notification delete scheduler interval time (86400)

- src/spaceone/notification/manager/identity_manager.py
- src/spaceone/notification/service/notification_service.py
feat: resource_type 'identity.Domain'
Add notification resource_type: identity.Domain (#123)
> feat: resource_type 'identity.Domain'

- src/spaceone/notification/manager/identity_manager.py
- src/spaceone/notification/service/notification_service.py
feat: get domain name
Get domain name for new email template (#124)
> feat: get domain name

- src/spaceone/notification/error/channel.py
- src/spaceone/notification/service/notification_service.py
feat: add validation check for domain
> feat: add validation check for domain

- src/spaceone/notification/manager/identity_manager.py
- src/spaceone/notification/service/notification_service.py
fix: update validation domain
Add notification resource_type: identity.Domain (#123)
> fix: update validation domain

- src/spaceone/notification/lib/schedule.py
- src/spaceone/notification/manager/notification_manager.py
- src/spaceone/notification/service/notification_service.py
feat: update delete all notifications
Delete multiple Notifications of specific user  (#129)
> feat: update delete all notifications

- src/spaceone/notification/service/notification_service.py
fix: modify user_id from meta
Delete multiple Notifications of specific user (#129)
> fix: modify user_id from meta

- src/spaceone/notification/manager/notification_manager.py
- src/spaceone/notification/service/notification_service.py
refactor: modify delete notifications for multiple
> refactor: modify delete notifications for multiple

- src/spaceone/notification/service/notification_service.py
fix: add filter_params for list notifications
> fix: add filter_params for list notifications

- src/spaceone/notification/model/notification_model.py
- src/spaceone/notification/model/user_channel_model.py
- src/spaceone/notification/service/notification_service.py
- src/spaceone/notification/service/project_channel_service.py
- src/spaceone/notification/service/user_channel_service.py
> refactor: change authorization scope

- src/spaceone/notification/info/user_channel_info.py
> fix: fix tags message type
